// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 删完之后的交代。三个数分开报，因为它们对用户的含义完全不同。
 */
export type ApplySummary = { 
/**
 * 进了回收站的条数。
 */
trashed: number, 
/**
 * 被安全机制挡下的条数（文件改过了、整组会被删空……）。**不是错误。**
 */
skipped: number, 
/**
 * 想删没删掉的。
 */
failed: number, reclaimed: number, 
/**
 * 头几条被跳过或失败的原因，给界面直接显示。全列出来在十万规模下没法看。
 */
notes: Array<string>, };
