// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioProfile = { enabled: boolean, 
/**
 * AAC-LC 码率（kbps）。默认 128。
 *
 * **下限 66 kbps 是 AudioToolbox 的硬约束**：请求 48k 实际输出 66k（ADR-003 实测），
 * 低于此值只会得到一个体积对不上预期的文件，不如直接钳住。
 */
bitrate_kbps: number, 
/**
 * AAC 源仅换容器不重新编码，避免二次劣化。
 */
copy_if_aac: boolean, };
