// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DedupProgress = { "stage": "walking", found: number, } | { "stage": "hashing", label: string, done: number, total: number, } | { "stage": "saving" };
