// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次去重扫描。
 */
export type DedupRun = { id: number, roots: Array<string>, 
/**
 * `exact` | `perceptual`。
 */
mode: string, 
/**
 * `scanning` | `ready` | `applying` | `done` | `cancelled`。
 */
status: string, 
/**
 * 感知模式的汉明距离阈值；精确模式为 `None`。
 */
threshold: number | null, };
