// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次去重的结果摘要。
 */
export type DedupReport = { run_id: number, 
/**
 * 参与比对的文件数。
 */
candidates: number, groups: number, 
/**
 * 每组只留一份的话，一共能省下多少字节。
 */
reclaimable: number, 
/**
 * 真读了全量内容的条数（精确模式）或算了指纹的条数（感知模式）。
 */
hashed: number, 
/**
 * 其中靠缓存省掉的。第二次跑同一批文件时这个数应该接近 `hashed`。
 */
cache_hits: number, cancelled: boolean, 
/**
 * 读不动的文件数。这些被排除，不会出现在任何分组里。
 */
errors: number, };
