// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 按目录的体积分布。
 */
export type DirGroup = { 
/**
 * 显示名。root 下的一级子目录名，直接躺在 root 里的文件归到 root 自己的名字。
 */
name: string, path: string, files: number, bytes: number, };
