// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chroma } from "./Chroma";

export type ImageProfile = { enabled: boolean, 
/**
 * 短边上限（px）。`0` = 不缩放。见 PROGRESS.md §4 短边约束规则。
 */
short_edge_cap: number, 
/**
 * AVIF 质量 0~100（`avifenc -q`）。默认 85（D-26）。
 */
quality: number, 
/**
 * 色度抽样。默认 444——截图上比 420 高约 14 分 SSIMULACRA2，体积仅 +3%（D-25）。
 */
chroma: Chroma, 
/**
 * `avifenc -s`，0 最慢最好、10 最快。默认 7（与 cwebp 同速但质量更高）。
 */
speed: number, 
/**
 * 动图（GIF/APNG/动画 WebP）→ 动画 AVIF 的 CRF。默认 32（D-27）。
 */
animated_crf: number, 
/**
 * 保留拍摄参数（EXIF / XMP，含 GPS 位置）。默认保留——归档的意义就在于
 * 这些信息，关掉只省几 KB。ICC 不受这个开关管：它是像素的解释方式，
 * 丢了整张图会偏色。
 */
keep_metadata: boolean, };
