// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 跨 IPC 边界传给前端的形态。
 *
 * 不直接给 `ZzError` 实现 `Serialize`：错误里可能带绝对路径和 stderr 原文，
 * 经过这一层可以明确控制暴露什么。
 */
export type IpcError = { code: string, message: string, };
