// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

/**
 * 队列界面与异常列表的一行。
 */
export type ItemRow = { id: number, src_path: string, kind: MediaKind, 
/**
 * `pending` / `running` / `done` / `skipped` / `failed`。
 */
status: string, src_size: number, dst_path: string | null, dst_size: number | null, elapsed_ms: number | null, skip_reason: string | null, 
/**
 * `skip_reason` 对应的中文说明，由后端查表得出。
 *
 * 让前端自己维护一份 `{ raw_excluded: "RAW 默认不处理…" }` 的话，两边迟早
 * 对不上——库里存的是 `as_str()`（`raw_excluded`），而 ts-rs 导出的枚举
 * 用的是 serde 名（`raw`），从类型上看就是两套词汇。
 */
skip_message: string | null, error_code: string | null, error_msg: string | null, attempt: number, };
