// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 任务面板要展示的汇总。一次查询算完，避免前端拉全表自己数。
 */
export type JobProgress = { total: bigint, done: bigint, failed: bigint, skipped: bigint, pending: bigint, running: bigint, 
/**
 * 已完成条目的源文件总字节。
 */
src_bytes: bigint, 
/**
 * 对应的输出总字节，两者相减即为已省下的空间。
 */
dst_bytes: bigint, };
