// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 送给界面的一帧进度。
 *
 * 计数全在内存里累加，**不是每次都去查库**：`job_progress` 是一条对 `items`
 * 的全表聚合，十万行乘以 10 Hz 就是把 SQLite 当秒表用。开跑时查一次做种，
 * 之后自己加。
 */
export type JobUpdate = { job_id: number, total: number, done: number, failed: number, skipped: number, 
/**
 * 还没处理完的条目数，**含在飞的那几件**（= `total - done - failed - skipped`）。
 */
pending: number, 
/**
 * 其中**此刻真的在编码**的条数，至多闸门那么宽（视频 2 + 轻活 `ncpu-2`）。
 *
 * 单列出来是为了让界面上的数和列表对得上：队列页「待处理」那一栏查的是
 * `status='pending'`，不含在飞的，所以它的徽标必须是 `pending - running`
 * （ADR-029）。恒等式 `pending - running == 库里 pending 的条数` 由「库里的
 * `running` 也在闸门放行那一刻写」保证（ADR-030）。
 */
running: number, 
/**
 * 已完成条目的源字节总和。
 */
src_bytes: number, 
/**
 * 对应的产物字节总和，两者相减即已省下的空间。
 */
dst_bytes: number, 
/**
 * 正在处理的文件，取最近开始的那一条。
 */
current: string, 
/**
 * 那一条的进度 0.0~1.0。图片管线不报进度，恒为 0。
 */
current_fraction: number, paused: boolean, 
/**
 * 卷不见了（R9）。任务已自动暂停，插回去点继续即可。
 */
volume_lost: string | null, 
/**
 * 剩余秒数。跑完时、或者库里没有逐件预估时（v5 之前扫的任务）为 `None`。
 */
eta_secs: number | null, 
/**
 * 这个任务**干了**多久，扣掉停着的那些段。跑完那一帧显示「耗时」用。
 *
 * 从进程这一次接手这个任务算起：中途退出应用再回来接着跑，这个数从头计。
 * 记在内存里而不是库里——为了一个展示用的数字，每 100 ms 写一次库不值当。
 */
elapsed_secs: number, 
/**
 * 最后一帧。界面靠它把「正在处理」那一行收掉。
 */
finished: boolean, 
/**
 * 任务**异常结束**的原因，正常跑完是 `None`。
 *
 * 有它才分得清「跑完了」和「死了」：出错那一帧由 [`crate::commands::job`]
 * 补发（记账线程已经随错误一起退了，发不出最后一帧），计数字段全是零。
 * 前端只看 `finished` 的话，会把一次配置错误显示成「✓ 已完成 压缩 0」。
 */
error: string | null, };
