// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 送给界面的一帧进度。
 *
 * 计数全在内存里累加，**不是每次都去查库**：`job_progress` 是一条对 `items`
 * 的全表聚合，十万行乘以 10 Hz 就是把 SQLite 当秒表用。开跑时查一次做种，
 * 之后自己加。
 */
export type JobUpdate = { job_id: number, total: number, done: number, failed: number, skipped: number, pending: number, 
/**
 * 已完成条目的源字节总和。
 */
src_bytes: number, 
/**
 * 对应的产物字节总和，两者相减即已省下的空间。
 */
dst_bytes: number, 
/**
 * 正在处理的文件，取最近开始的那一条。
 */
current: string, 
/**
 * 那一条的进度 0.0~1.0。图片管线不报进度，恒为 0。
 */
current_fraction: number, paused: boolean, 
/**
 * 卷不见了（R9）。任务已自动暂停，插回去点继续即可。
 */
volume_lost: string | null, 
/**
 * 剩余秒数。**样本不足时为 `None`**——开头几秒的速率毫无参考价值，
 * 显示一个乱跳的数字比不显示更糟。
 */
eta_secs: number | null, 
/**
 * 最后一帧。界面靠它把「正在处理」那一行收掉。
 */
finished: boolean, 
/**
 * 任务**异常结束**的原因，正常跑完是 `None`。
 *
 * 有它才分得清「跑完了」和「死了」：出错那一帧由 [`crate::commands::job`]
 * 补发（记账线程已经随错误一起退了，发不出最后一帧），计数字段全是零。
 * 前端只看 `finished` 的话，会把一次配置错误显示成「✓ 已完成 压缩 0」。
 */
error: string | null, };
