// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";
import type { Range } from "./Range";

/**
 * 按媒体类型的一组。
 */
export type KindGroup = { kind: MediaKind, files: bigint, src_bytes: bigint, out_bytes: Range, seconds: Range, };
