// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 编码任务跑在哪条流水线上。CPU 与媒体引擎是独立硅片，可并行（D-07）。
 */
export type Lane = "cpu" | "media_engine";
