// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

/**
 * 一个文件的规格。源和产物各一份，界面并排摆。
 */
export type MediaSpec = { kind: MediaKind, size_bytes: number, 
/**
 * 已按朝向换算过的显示尺寸。音频是 0×0。
 */
width: number, height: number, 
/**
 * 给人看的编码名：`HEIC` / `JPEG` / `AVIF` / `HEVC` / `H.264` / `AAC`。
 * 认不出来就是 `None`，界面显示「—」。
 */
format: string | null, 
/**
 * 平均码率 bps，`体积 × 8 ÷ 时长` 现算。图片没有码率。
 */
bitrate_bps: number | null, duration_us: number | null, };
