// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前勾选待删的量。确认框上要说的就是这两个数。
 */
export type PendingRemovals = { count: number, bytes: number, };
