// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "./Preset";
import type { Profile } from "./Profile";

export type PresetInfo = { id: Preset, description: string, profile: Profile, };
