// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioProfile } from "./AudioProfile";
import type { ImageProfile } from "./ImageProfile";
import type { OutputProfile } from "./OutputProfile";
import type { VideoProfile } from "./VideoProfile";

/**
 * 一次任务的完整配置快照。
 */
export type Profile = { image: ImageProfile, video: VideoProfile, audio: AudioProfile, output: OutputProfile, };
