// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 带上下界的估计。`mid` 用来显示和排序，`low`/`high` 用来说明「大概这个范围」。
 */
export type Range = { low: number, mid: number, high: number, };
