// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Access } from "./Access";

/**
 * 一个待扫描根目录的可读性。
 */
export type RootAccess = { path: string, access: Access, };
