// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";

/**
 * 保存配置的结果。越界值会被钳到合法范围而不是报错，
 * `fixes` 用来在界面上提示「你填的 3000 被改成了 100」。
 */
export type SaveResult = { profile: Profile, fixes: Array<string>, };
