// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirGroup } from "./DirGroup";
import type { KindGroup } from "./KindGroup";
import type { Range } from "./Range";
import type { SkipGroup } from "./SkipGroup";

/**
 * 扫描报告。
 */
export type ScanReport = { roots: Array<string>, 
/**
 * 遍历到的普通文件总数（含非媒体）。
 */
files_seen: bigint, 
/**
 * 其中被认作媒体的。
 */
media_found: bigint, 
/**
 * 读目录 / 读属性失败的次数。数值大通常意味着权限不足（R16）。
 */
errors: bigint, hardlinks_skipped: bigint, cancelled: boolean, 
/**
 * 将要处理的文件数与源字节。**不含跳过项**。
 */
planned_files: bigint, planned_bytes: bigint, out_bytes: Range, saved_bytes: Range, 
/**
 * 墙钟总耗时预估：两条队列取较慢的一条（D-42）。
 */
seconds: Range, cpu_seconds: Range, hw_seconds: Range, groups: Array<KindGroup>, skipped: Array<SkipGroup>, skipped_files: bigint, skipped_bytes: bigint, dirs: Array<DirGroup>, };
