// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirGroup } from "./DirGroup";
import type { KindGroup } from "./KindGroup";
import type { Range } from "./Range";
import type { SkipGroup } from "./SkipGroup";

/**
 * 扫描报告。
 */
export type ScanReport = { 
/**
 * 这次扫描落下的任务 id。处理计划已经写进库了，按「开始」就是跑它。
 */
job_id: number, roots: Array<string>, 
/**
 * 遍历到的普通文件总数（含非媒体）。
 */
files_seen: number, 
/**
 * 其中被认作媒体的。
 */
media_found: number, 
/**
 * 读目录 / 读属性失败的次数。数值大通常意味着权限不足（R16）。
 */
errors: number, hardlinks_skipped: number, cancelled: boolean, 
/**
 * 下面三个数只在**镜像模式**下有意义：它们是源目录里有、而输出目录里
 * 不会有的东西（ADR-021 §13）。界面据此告诉用户「输出目录不是源目录的
 * 完整副本」——不说清楚，用户对着输出目录点头再删源盘，丢的就是这些。
 *
 * 扩展名不认识的普通文件：文档、压缩包、工程文件。
 */
non_media_files: number, 
/**
 * 边车文件：`.xmp` / `.aae` 这类紧挨着照片的编辑记录。最要紧的一类——
 * 它们依附于被压缩的那些照片，丢了就是丢了人家的调色参数。
 */
sidecar_files: number, 
/**
 * 整个跳过的包目录：`.photoslibrary` / `.fcpbundle` / `.app`。
 */
bundles_skipped: number, 
/**
 * 将要处理的文件数与源字节。**不含跳过项**。
 */
planned_files: number, planned_bytes: number, out_bytes: Range, saved_bytes: Range, 
/**
 * 墙钟总耗时预估。已按闸门宽度折过并发，见 `estimate::Estimate::wall_clock`。
 */
seconds: Range, 
/**
 * 视频队列串行跑完要多久（未折并发）。下面这条是图片与音频。
 * 两条**不必**加起来等于 `seconds`——那正是并发省下来的部分。
 */
video_seconds: Range, light_seconds: Range, groups: Array<KindGroup>, skipped: Array<SkipGroup>, skipped_files: number, skipped_bytes: number, dirs: Array<DirGroup>, };
