// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirGroup } from "./DirGroup";
import type { KindGroup } from "./KindGroup";
import type { Range } from "./Range";
import type { SkipGroup } from "./SkipGroup";

/**
 * 扫描报告。
 */
export type ScanReport = { roots: Array<string>, 
/**
 * 遍历到的普通文件总数（含非媒体）。
 */
files_seen: number, 
/**
 * 其中被认作媒体的。
 */
media_found: number, 
/**
 * 读目录 / 读属性失败的次数。数值大通常意味着权限不足（R16）。
 */
errors: number, hardlinks_skipped: number, cancelled: boolean, 
/**
 * 将要处理的文件数与源字节。**不含跳过项**。
 */
planned_files: number, planned_bytes: number, out_bytes: Range, saved_bytes: Range, 
/**
 * 墙钟总耗时预估。已按闸门宽度折过并发，见 `estimate::Estimate::wall_clock`。
 */
seconds: Range, 
/**
 * 视频队列串行跑完要多久（未折并发）。下面这条是图片与音频。
 * 两条**不必**加起来等于 `seconds`——那正是并发省下来的部分。
 */
video_seconds: Range, light_seconds: Range, groups: Array<KindGroup>, skipped: Array<SkipGroup>, skipped_files: number, skipped_bytes: number, dirs: Array<DirGroup>, };
