// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 跳过一个文件的原因。
 *
 * 全项目共用一份：`as_str()` 会直接写进 `items.skip_reason`，是稳定标识符，
 * 改动等于改数据格式；`message()` 是给人看的，可以随便改。
 */
export type SkipReason = "disabled" | "raw" | "too_small" | "already_optimal" | "hdr" | "too_large" | "no_gain" | "low_quality" | "src_changed" | "src_missing";
