// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipReason } from "./SkipReason";

/**
 * 按跳过原因的一组。
 */
export type SkipGroup = { reason: SkipReason, 
/**
 * 面向用户的说明，直接取自 [`SkipReason::message`]，前端不必自己维护一份文案。
 */
message: string, files: number, bytes: number, };
