// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredMember } from "./StoredMember";

/**
 * 库里读出来的一组，连成员一起。
 */
export type StoredGroup = { id: number, hash: string, reclaimable: number, members: Array<StoredMember>, };
