// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoredMember = { id: number, path: string, size: number, mtime: number, 
/**
 * 到代表元的汉明距离。精确组恒为 0。
 */
distance: number, 
/**
 * `true` = 留下。默认全 `true`，见 [`Db::save_dedup_groups`]。
 */
keep: boolean, 
/**
 * `None` = 还没动；`trashed` | `failed`。
 */
disposal: string | null, };
