// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 外部工具就绪情况。缺工具时界面要能明确说清缺哪个，而不是等到跑任务才失败。
 */
export type ToolStatus = { ffmpeg: string | null, ffprobe: string | null, };
