// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitDepth } from "./BitDepth";
import type { Lane } from "./Lane";
import type { X265Preset } from "./X265Preset";

export type VideoProfile = { enabled: boolean, 
/**
 * 短边上限（px）。`0` = 不缩放。
 */
short_edge_cap: number, 
/**
 * 帧率上限。`0` = 不限制。高于此值的源会被降帧。
 */
fps_cap: number, 
/**
 * x265 CRF。默认 24（D-04）。
 */
crf: number, 
/**
 * x265 preset。
 */
preset: X265Preset, 
/**
 * 位深。默认 8-bit——实测 10-bit 仅小 0.6%、VMAF 仅高 0.06，却慢 49~70%（D-13/D-20）。
 */
bit_depth: BitDepth, 
/**
 * 编码通道。默认 CPU 软编：硬编等 VMAF 体积约为软编 2 倍（D-24）。
 */
lane: Lane, 
/**
 * 硬编质量（`hevc_videotoolbox -q:v`），仅 `lane = MediaEngine` 时生效。
 */
hw_quality: number, 
/**
 * 跳过 HDR 源。v1 默认开启——转码会丢 BT.2020/PQ 元数据导致画面发灰（R4）。
 */
skip_hdr: boolean, };
