// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitDepth } from "./BitDepth";
import type { Lane } from "./Lane";
import type { X265Preset } from "./X265Preset";

export type VideoProfile = { enabled: boolean, 
/**
 * 短边上限（px）。`0` = 不缩放。
 */
short_edge_cap: number, 
/**
 * 帧率上限。`0` = 不限制。高于此值的源会被降帧。
 */
fps_cap: number, 
/**
 * x265 CRF。默认 24（D-04）。
 */
crf: number, 
/**
 * x265 preset。
 */
preset: X265Preset, 
/**
 * 位深。默认 8-bit——实测 10-bit 仅小 0.6%、VMAF 仅高 0.06，却慢 49~70%（D-13/D-20）。
 */
bit_depth: BitDepth, 
/**
 * 编码通道。默认 CPU 软编：硬编等 VMAF 体积约为软编 2 倍（D-24）。
 */
lane: Lane, 
/**
 * 硬编质量（`hevc_videotoolbox -q:v`），仅 `lane = MediaEngine` 时生效。
 */
hw_quality: number, 
/**
 * 跳过 HDR 源。v1 默认开启——转码会丢 BT.2020/PQ 元数据导致画面发灰（R4）。
 */
skip_hdr: boolean, 
/**
 * VMAF 质量门禁下限（0~100）。低于此分的产物直接丢弃、保留原文件。`0` = 关闭。
 *
 * 默认 80：这是一条**兜底线，不是画质目标**。
 *
 * 默认档（短边 1080 / 30fps / x265 medium / CRF 24）在四组真实素材上实测
 * 96.13~99.04，离 80 有十几分余量；连 CRF 32 都还在 89.86~93.24（基准 9）。
 * 换句话说 80 分之下基本只剩「编码器出了岔子」那一类——参数写错、素材极端难压、
 * 硬编掉档。日常调 CRF 不会撞到它。
 *
 * 想让门禁真正参与画质决策（比如卡住 CRF 32 那一档）需要 95 左右；这里选 80 是
 * 刻意把它退成安全网，把「压多狠」的决定权交回给 CRF。
 */
vmaf_min: number, };
